# Generated by Django 6.0.7 on 2026-08-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='subtitle',
        ),
    ]
