# Generated by Django 6.0.7 on 2026-08-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_remove_story_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
