# Generated by Django 6.0.7 on 2026-09-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_alter_story_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
