# Generated by Django 6.0.7 on 2026-10-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_storyaudit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoryAudit',
        ),
    ]
